### ISSUE TITLE
NOT WORKING AT ALL !!!

### ISSUE THREAD

**Issue by Rui1009** [koska-devs/SlickTutorial#1]
## summary
this repo has a critical issue.
we show the error in build.sbt file when we add import sentence of slick at the top because slick is not added at plugin.sbt file.
You should fix this problem as soon as you can.
As my advise to you, it enable you to write the better code to re-check your code carefully after you develop.

**Comment by Rui1009** [comment]
@sonken625

**Comment by sonken625** [comment]
だまらっしゃい
